### PR TITLE
Merge branch 'develop'

### PR DESCRIPTION
**Pull request by lhkhang**

### CODE REVIEW

**Review by lhkhang — COMMENTED** [review]
reviewed

**Comment by dan-bowen** [comment]
Nice job on this.

Sadly we seem to have lost the Travis build so there are no automated builds & tests running currently. Can you verify the tests are still passing with `make test`?

If the tests pass I think this is good to merge.

P.S. This is being published to [Packagist](https://packagist.org/packages/chargely/chargify-sdk-php). Cutting a new release should just mean a new tag like `v1.0.0`.

**Comment by lhkhang** [comment]
[testdox.txt](https://github.com/crucialwebstudio/chargify-sdk-php/files/14718345/testdox.txt)
Yes, it was able to pass the phpunit test. The attachment is the test result.

**Review by dan-bowen — APPROVED** [review]
Awesome. Love to see the passing tests.

**Pull request merged**
